---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: DOC는 docs.netapp.com 에서 NetApp의 세대 AI 기반 보조자입니다. DOC는 docs.NetApp.com에 게시된 콘텐츠를 사용하여 NetApp 제품에 대한 질문에 응답하도록 설계되었습니다. 
---
= NetApp 생성 AI 기반 보조 개요
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC는 docs.netapp.com 에서 NetApp의 세대 AI 기반 보조자입니다. DOC는 docs.NetApp.com에 게시된 콘텐츠를 사용하여 NetApp 제품에 대한 질문에 응답하도록 설계되었습니다.

DOC는 이전 질문에서 응답을 작성하고, 추가 질문을 제안하고, 응답을 생성하는 방법을 설명할 수 있습니다. 따라서 NetApp 설명서를 탐색하는 데 유용한 도구가 됩니다.



== 범위 및 제한 사항

DOC는 docs.NetApp.com에 게시된 특정 콘텐츠를 기반으로 한 질문에만 답할 수 있습니다.


NOTE: 베타 단계에서 Doc은 docs.netapp.com에 게시된 대부분의 콘텐츠를 활용하지만, 모든 콘텐츠를 활용하는 것은 아닙니다. Doc은 ONTAP, BlueXP, StorageGRID, E-Series, Keystone, SnapCenter 관련 모든 문서에 익숙하며, 해당 제품 관련 질문에 답변합니다. 반면, 일부 기존 제품 관련 문서에는 익숙하지 않습니다. 예를 들어, Doc은 SnapDrive for UNIX 문서를 활용하여 답변을 제공하지 않습니다. 베타 기간 동안 Doc의 지식을 더욱 발전시키기 위해 노력하고 있습니다. Doc이 제공하지 않는 정보가 필요하시면 mailto:ng-doccomments@netapp.com[문의]으로 문의해 주세요.

* Doc은 제품의 최신 버전에 대해서만 질문에 답변합니다. 예를 들어, 제품의 1.0 버전과 2.0 버전에 대한 설명서가 있는 경우, Doc은 최신 2.0 설명서만 참조합니다.
* 최상의 결과를 얻으려면 제품 이름을 항상 구체적으로 지정하세요. Doc은 질문을 할 때 사용자가 어떤 페이지에 있는지 알고 있지만, 이는 Doc이 답변을 작성할 때 고려하는 여러 요소 중 하나일 뿐입니다.
* DOC는 docs.NetApp.com에서 지원되는 언어로 채팅할 수 있지만 영어 이외의 버전에 대해서는 교육을 받지 않았습니다.




== 양호한 프롬프트 작성

Docs를 가장 잘 사용하려면 다음 팁을 따르십시오.

구체적인 질문을 합니다.:: 자세한 질문을 작성하고 제품 이름, 버전 및 인터페이스 유형(GUI, API)을 지정합니다. 예를 들면 다음과 같습니다.
+
--
[]
====
ONTAP 9.8에서 ONTAP 9.12.1로 업그레이드하려면 System Manager에서 어떤 단계를 따라야 합니까?

====
--
작업을 완료하기 위한 단계를 요청합니다.:: Doc에게 프로세스를 완료하는 단계를 포함시키도록 요청합니다. "BlueXP  커넥터를 인터넷에 연결하지 않고 설치하려면 어떻게 해야 합니까?"라는 질문 대신 다음을 시도해 보십시오.
+
--
[]
====
인터넷없이 BlueXP  커넥터를 설치하려면 어떤 단계를 따라야 합니까?

====
--
복잡한 질문을 덩어리로 나눕니다.:: 복잡한 질문을 작은 질문으로 나눕니다(_chaining_이라고도 함). DOC는 이전 질문을 기억하고 채팅을 계속하면서 보다 복잡한 답변을 작성합니다.
+
--
예를 들어, Doc_BlueXP 에서 랜섬웨어 차단 및 백업 일정을 어떻게 구성합니까?_try:

[]
====
BlueXP 에서 랜섬웨어 보호를 구성하는 단계는 무엇입니까?

====
그런 다음 질문:

[]
====
BlueXP 에서 백업 일정을 구성하는 단계는 무엇입니까?

====
--
따옴표를 사용합니다.:: 여러 단어로 된 구를 따옴표로 묶습니다. 이를 통해 Doc은 이 문구를 하나의 개념으로 인식할 수 있으며, 이는 인간과의 대화에서 강조하는 방법과 유사합니다.
+
--
예를 들어, 이 질문에서 _ ONTAP에서 스토리지 효율성을 계산하는 방법은 무엇입니까?_Doc은 _ 스토리지 _ 및 _ 효율성 _ 에 대해 관련 없는 두 단어로 물어볼 것입니다. 대신 다음을 시도해 보십시오.

[]
====
ONTAP에서 "스토리지 효율성"을 어떻게 계산합니까?

====
--
Doc이 어떻게 응답했는지 검토합니다.:: 이에 대한 답변을 통해 Doc은 어떻게 대응이 이루어졌는지에 대한 통찰력을 제공합니다. 이렇게 하면 원하는 결과를 얻기 위해 질문을 구체화하는 방법에 대한 아이디어를 얻을 수 있습니다.
채팅 기록을 지웁니다:: 주제를 변경하려면(예: 다른 제품에 대해 문의하려는 경우) 채팅 기록을 삭제하고 새 세션을 시작하세요. 새 주제를 시작하기 전에 채팅 기록을 삭제하지 않으면 부정확한 결과가 나올 수 있습니다.




== 피드백

Dell은 Docs를 지속적으로 개선하기 위해 노력하고 있습니다. Doc의 채팅 창에 피드백을 보내 주십시오. Doc의 답변이 정확하고 유용한지 또는 불완전한지 또는 어떤 식으로든 불충분한지 알려주십시오. 문서의 기능 또는 응답과 관련하여 궁금한 점이나 우려사항이 있으면 mailto:ng-doccomments@netapp.com [연락처]로 문의해 주십시오.
