---
sidebar: sidebar 
permalink: doc-gen-ai-assistant-terms-of-use.html 
keywords:  
summary: DOC는 docs.netapp.com 에서 NetApp의 세대 AI 기반 보조자입니다. DOC는 docs.NetApp.com에 게시된 콘텐츠를 사용하여 NetApp 제품에 대한 질문에 응답하도록 설계되었습니다. 예를 들어, Doc은 NetApp 스토리지 효율성 기능이나 멀티 클라우드 환경에 대한 백업 및 복구 모범 사례에 대한 질문에 응답할 수 있습니다. 
---
= NetApp 생성 AI 기반 보조 사용 약관
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC는 docs.netapp.com 에서 NetApp의 세대 AI 기반 보조자입니다. DOC는 docs.NetApp.com에 게시된 콘텐츠를 사용하여 NetApp 제품에 대한 질문에 응답하도록 설계되었습니다. 예를 들어, Doc은 NetApp 스토리지 효율성 기능이나 멀티 클라우드 환경에 대한 백업 및 복구 모범 사례에 대한 질문에 응답할 수 있습니다.

이 베타 버전의 Doc은 오류나 부정확함이 포함될 수 있는 알고리즘으로 생성된 콘텐츠를 생성합니다. 생성된 모든 콘텐츠는 시작점으로만 사용해야 합니다. NetApp의 공식 제품 설명서를 참조하여 항상 Doc의 응답을 확인해야 합니다. 문서 작성 답변에 대한 신뢰는 귀하의 책임이며, NetApp는 문서 작성 응답을 단독으로 사용하여 발생할 수 있는 문제나 어려움에 대해 책임을 지지 않습니다.



== 조건

Doc을 사용함으로써 귀하는 콘텐츠 및 응답을 생성할 때 다음 규칙 및 규정을 준수하는 데 동의합니다. 본 약관을 준수하지 않을 경우 문서 사용이 차단될 수 있습니다.

* Doc을 사용하여 유해, 남용, 폭력 또는 기망을 유발할 수 있는 콘텐츠를 제작하려고 하지 마십시오.
* Doc이 의도한 목적이 아닌 대화에서 사용하거나 NetApp 제품에 관한 질문이 아닌 질문에 답변하려고 해서는 안 됩니다.




== 피드백

Dell은 Docs를 지속적으로 개선하기 위해 노력하고 있습니다. Doc의 채팅 창에 피드백을 보내 주십시오. Doc의 답변이 정확하고 유용한지 또는 불완전한지 또는 어떤 식으로든 불충분한지 알려주십시오. 문서의 기능 또는 응답과 관련하여 궁금한 점이나 우려사항이 있으면 mailto:ng-doccomments@netapp.com [연락처]로 문의해 주십시오.
