---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords:  
summary: DOC는 docs.netapp.com 에서 NetApp의 세대 AI 기반 보조자입니다. DOC는 NetApp 제품에 대한 질문에 응답하도록 설계되었습니다. 예를 들어, Doc은 NetApp 스토리지 효율성 기능이나 멀티 클라우드 환경에 대한 백업 및 복구 모범 사례에 대한 질문에 응답할 수 있습니다. 
---
= NetApp 생성 AI 도우미 사용 약관
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC는 docs.netapp.com 에서 NetApp의 세대 AI 기반 보조자입니다. DOC는 NetApp 제품에 대한 질문에 응답하도록 설계되었습니다. 예를 들어, Doc은 NetApp 스토리지 효율성 기능이나 멀티 클라우드 환경에 대한 백업 및 복구 모범 사례에 대한 질문에 응답할 수 있습니다.

이 베타 버전의 Doc은 오류나 부정확함이 포함될 수 있는 알고리즘으로 생성된 콘텐츠를 생성합니다. 생성된 모든 콘텐츠는 시작점으로만 사용해야 합니다. NetApp의 공식 제품 설명서를 참조하여 항상 Doc의 응답을 확인해야 합니다. 문서 작성 답변에 대한 신뢰는 귀하의 책임이며, NetApp는 문서 작성 응답을 단독으로 사용하여 발생할 수 있는 문제나 어려움에 대해 책임을 지지 않습니다.



== 조건

Doc을 사용함으로써 귀하는 콘텐츠 및 응답을 생성할 때 다음 규칙 및 규정을 준수하는 데 동의합니다. 본 약관을 준수하지 않을 경우 문서 사용이 차단될 수 있습니다.

* Doc을 사용하여 유해, 남용, 폭력 또는 기망을 유발할 수 있는 콘텐츠를 제작하려고 하지 마십시오.
* Doc이 의도한 목적이 아닌 대화에서 사용하거나 NetApp 제품에 관한 질문이 아닌 질문에 답변하려고 해서는 안 됩니다.




== 제공합니다

* DOC는 코끼리가 아니지만 상당히 기억이 있습니다.
+
대부분의 경우 Doc은 여러분이 논의하는 내용을 기억하고 주의를 기울입니다. 문서가 대화를 추적하지 못하면 동일한 채팅 세션에서 새 대화를 시작할 수 있습니다.

* DOC는 열정적인 독자입니다.
+
우리의 문서가 docs.netapp.com (그리고 많은 일이 발생)에 게시될 때마다, Doc은 읽고 그 응답을 생성하기 위해 그들을 참조 할 수 있습니다. Doc이 얼마나 빠르게 학습하는지는 놀랍습니다.

* DOC는 상담적입니다.
+
DOC는 여러분이 질문한 것 외에 여러분이 질문할 수 있는 질문들에 대한 제안을 제공합니다.

* DOC는 의사 소통적입니다.
+
DOC는 응답을 생성하는 방법에 대한 인사이트를 공유함으로써 질문을 다시 표현할 수 있는 기회를 제공합니다.





== 제한 사항

* NetApp 제품에 여러 버전의 문서가 있는 경우, Doc은 답변을 구할 수 있도록 최신 버전만을 참조합니다.
* 베타 기간 동안 Doc은 모든 NetApp 제품에 대한 모든 문서를 참조하지 않습니다. DOC는 답변을 생성하는 데 도움이 되는 ONTAP 및 BlueXP  문서를 포함하지만 이에 국한되지 않는 문서의 하위 집합만을 지칭합니다.
* Doc은 다른 언어로 답변을 제공할 수 있지만 영어 이외의 버전의 NetApp 제품 문서를 읽지 않았습니다. 가능한 한 가장 정확한 정보를 얻기 위해 항상 문서의 응답을 영어로 확인합니다.




== 팁

* DOC는 구체적인 질문을 매우 좋아합니다.
+
DOC는 제품 이름, 인터페이스(예: GUI 또는 API) 및 버전을 명시적으로 인용할 때 더 나은 응답을 제공합니다. 예: _ ONTAP 9.8에서 ONTAP 9.12.1로 업그레이드하려면 System Manager에서 어떤 단계를 따라야 합니까? _

* 어떤 일을 하는 방법을 배울 필요가 있습니까?
+
Doc에 단계를 포함하도록 요청합니다. _인터넷 없이 BlueXP  커넥터를 설치하려면 어떻게 해야 합니까?_인터넷 없이 BlueXP  커넥터를 설치하려면 어떤 단계를 따라야 합니까? _

* 간단한 질문을 합니다.
+
복잡한 질문을 해야 하는 경우, 작은 질문으로 나눕니다(이를 체인 질문이라고도 함). 채팅 세션 중에 Doc은 주의를 기울이고 여러분이 질문한 사항을 기억합니다.

+
Doc_BlueXP 에서 랜섬웨어 방지 및 백업 일정을 어떻게 구성합니까?_try_BlueXP 에서 랜섬웨어 보호를 구성하는 단계는 무엇입니까? _ 및 _ BlueXP 에서 백업 일정을 구성하는 단계는 무엇입니까? _

* 따옴표를 사용하여 Doc에서 오해할 수 있는 여러 단어로 된 구에 주의를 기울이도록 할 시기를 지정합니다.
+
예를 들어, Doc_ONTAP에서 스토리지 효율성은 어떻게 계산됩니까?_라고 물을 경우 이는 관련이 없는 두 단어로 스토리지 및 효율성에 대해 질문한다고 생각할 수 있습니다. Doc이 (개념)스토리지 효율성에 대해 질문한다는 것을 이해하고 있음을 뜻하도록 해당 문구를 따옴표로 묶습니다. _ ONTAP에서 "스토리지 효율성"은 어떻게 계산됩니까? _

+
당신은 사람과 대화를 하고 있다면, 당신은 아마 문구를 강조하거나, 아마도 공표 또는 어떤 방식으로 구별을 명확하게 만드는 제스처를 사용할 수 있습니다. Double-quotes는 Doc이 말하는 내용을 이해하는 데 도움이 되는 제스처라고 생각합니다.

* 이에 대한 답변을 통해 Doc은 어떻게 대응이 이루어졌는지에 대한 통찰력을 제공합니다. 호기심을 가지십시오.
+
질문을 할 때 다른 패턴과 접근법을 시도해 보십시오. 원하는 결과를 얻지 못한 경우 질문을 바꿔 보세요.





== 피드백

Dell은 Docs를 지속적으로 개선하기 위해 노력하고 있습니다. Doc의 채팅 창에 피드백을 보내 주십시오. Doc의 답변이 정확하고 유용한지 또는 불완전한지 또는 어떤 식으로든 불충분한지 알려주십시오. 문서의 기능 또는 응답과 관련하여 궁금한 점이나 우려사항이 있으면 mailto:ng-doccoments@netapp.com [연락처]로 문의해 주십시오.
