---
sidebar: sidebar 
permalink: docs-netapp-com.html 
keywords:  
summary:  
---
= docs.netapp.com 사이트 정보
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


.사이트 투어
video::77a636ba-4202-45bb-9e47-b08a01138502[panopto]
.스크립트
[%collapsible]
====
0:01:: 안녕. docs.netapp.com 팀의 Ben입니다. 이 비디오에서는 콘텐츠 시청 환경을 최대한 활용할 수 있도록 docs.netapp.com 에서 사용할 수 있는 기능과 특징에 대해 살펴봅니다.
0:12:: 먼저 원하는 콘텐츠를 찾아 보겠습니다. 문서 사이트를 입력한 후에는 사이트의 왼쪽을 사용하여 탐색할 수 있습니다.
0:20:: 여러 버전의 문서를 사용할 수 있는 경우 사용 중인 제품 버전에 대한 문서를 선택할 수 있습니다.
0:28:: 검색 상자를 사용하여 문서 사이트 내의 콘텐츠를 찾습니다. 예를 들어, 볼륨 암호화의 작동 방식을 익히고 싶습니다.
0:36:: 문서를 찾아보려면 목차를 사용할 수 있습니다. 목차는 제품 시작 및 사용과 같은 논리적 그룹으로 구성되어 있습니다.
0:45:: 다른 문서 사이트로 이동하려면 Breadcrumb를 사용하여 docs.netapp.com 주위를 탐색할 수 있습니다.
0:50:: 원하는 콘텐츠를 찾으면 몇 가지 주요 기능을 사용하여 콘텐츠와 상호 작용할 수 있습니다.
0:58:: 대부분의 문서 사이트는 여러 언어로 제공되므로 기본 설정 언어로 문서를 읽을 수 있습니다.
1:05:: 페이지에 여러 섹션이 있는 경우 "이 페이지에" 링크를 사용하여 원하는 콘텐츠로 바로 이동할 수 있습니다. 또한 이 링크는 페이지에서 현재 위치를 식별하므로 스크롤할 때 따라가는 데 도움이 됩니다.
1:20:: 콘텐츠 자체에 초점을 맞추려면 왼쪽 및 오른쪽 사이드바를 축소할 수 있습니다. 작업을 마치면 탐색 컨트롤을 다시 보려면 해당 컨트롤을 확장합니다.
1:33:: 문서를 오프라인으로 읽어야 하는 경우 전체 문서 사이트 또는 사이트 내의 개별 섹션의 PDF를 다운로드할 수 있습니다.
1:41:: NetApp 문서는 오픈 소스이며 GitHub 계정을 사용하여 커뮤니티 참여를 허용하도록 설계되었습니다. 피드백을 제출하여 문서 업데이트를 요청하거나 직접 콘텐츠를 편집하십시오. 이 내용은 병합 전에 NetApp 콘텐츠 리드에 제출됩니다.
1:59:: 일부 클라우드 서비스의 문서 사이트에는 문서를 특정 클라우드 공급자로 필터링할 수 있는 클라우드 공급자 옵션이 표시될 수 있습니다. 예를 들어 Microsoft Azure를 선택하면 Azure에 적용되는 콘텐츠만 표시됩니다. 다른 클라우드 공급자의 콘텐츠는 표시되지 않습니다.
2:18:: 태블릿, 모바일 장치 또는 데스크톱에서 콘텐츠에 액세스할 수 있으므로 Microsoft는 모든 장치에서 문서가 잘 보이도록 반응형 레이아웃을 사용합니다.
2:28:: 이제 끝이군요. 이러한 기능을 즐겁게 사용해주시길 바라며 컨텐츠 커뮤니티의 일원이 되어 주셔서 감사합니다.


====