---
settings:
  name: About docs.netapp.com
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: 사이트 정보
    url: "/docs-netapp-com.html"
  - title: Doc (AI 기반 비서) 정보
    entries:
    - title: 기능 및 제한 사항
      url: "/doc-gen-ai-assistant.html"
    - title: 이용 약관
      url: "/doc-gen-ai-assistant-terms-of-use.html"
  - title: 법적 고지
    url: "/legal-notices.html"
