---
settings:
  name: About docs.netapp.com
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 사이트 정보
    url: "/docs-netapp-com.html"
  - title: Doc (AI 기반 비서) 정보
    url: "/doc-gen-ai-assistant.html"
  - title: 법적 고지
    url: "/legal-notices.html"
